### ISSUE TITLE
Build fails in Docker image

### ISSUE THREAD

**Issue by 417-72KI** [yonaskolb/Mint#196]
## Dockerfile

```dockerfile
ARG SWIFT_VERSION=latest
FROM swift:${SWIFT_VERSION}

LABEL maintainer "417-72KI <417.72ki@gmail.com>"

ARG MINT_REVISION=master
ENV MINT_REVISION=${MINT_REVISION}

# Install Mint
RUN git clone -b "${MINT_REVISION}" --depth 1 "https://github.com/yonaskolb/Mint.git" ~/Mint && \
    cd ~/Mint && \
    swift run mint install yonaskolb/mint && \
    cd && \
    rm -rf ~/Mint

CMD [ "/bin/bash" ]
```

## Error

```sh
/root/Mint/Sources/MintKit/ProcessInfoExtensions.swift:12:61: error: use of unresolved identifier '_SYS_NAMELEN'
        let data = Data(bytes: &sysinfo.machine, count: Int(_SYS_NAMELEN))
                                                            ^~~~~~~~~~~~
```

It seems to be caused by #185.
