### PR TITLE
Skip Apple Silicon supporting flow on Linux platform.

### LINKED ISSUE #196: Build fails in Docker image
## Dockerfile

```dockerfile
ARG SWIFT_VERSION=latest
FROM swift:${SWIFT_VERSION}

LABEL maintainer "417-72KI <417.72ki@gmail.com>"

ARG MINT_REVISION=master
ENV MINT_REVISION=${MINT_REVISION}

# Install Mint
RUN git clone -b "${MINT_REVISION}" --depth 1 "https://github.com/yonaskolb/Mint.git" ~/Mint && \
    cd ~/Mint && \
    swift run mint install yonaskolb/mint && \
    cd && \
    rm -rf ~/Mint

CMD [ "/bin/bash" ]
```

## Error

```sh
/root/Mint/Sources/MintKit/ProcessInfoExtensions.swift:12:61: error: use of unresolved identifier '_SYS_NAMELEN'
        let data = Data(bytes: &sysinfo.machine, count: Int(_SYS_NAMELEN))
                                                            ^~~~~~~~~~~~
```

It seems to be caused by #185.

### PR DESCRIPTION
**Pull request by 417-72KI**
Resolves #196 

[`ProcessInfo.machineHardwareName`](https://github.com/yonaskolb/Mint/pull/185/files#diff-e90019304d64f8d341431032f67544626424aaa233785b85ba42667c4a69a61dR7) has caused a compile error on Linux platform.
However, it was not called on Linux platform, so I made it only available on macOS platform.

Furthermore, I added the test on Linux which has been missed in #158 .

### CODE REVIEW

**Review by yonaskolb — APPROVED** [review]
Fantastic, thanks @417-72KI
